language: cpp
compiler:
 - gcc

sudo: false
dist: trusty
# Blacklist
branches:
  except:
    - gh-pages
    
# Environment variables
env:
  global:
    - GH_REPO_NAME: BigBlueBox
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/rbaker26/BigBlueBox.git
    
# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 #- pip install --user cpp-coveralls

install:
 - sudo apt-get update
 - sudo apt-get install qt5-default qttools5-dev-tools
 
script:
 #- ./configure --enable-gcov && make && make check
 - qmake "CONFIG+=test" src/BigBlueBox.pro #we gonna compile for Unit test first
 - clang -coverage
 - ./BigBlueBox #run unit test
 - rm Makefile BigBlueBox *.o #remove files (which are generated from unit test) for next build
 
after_success:
 - bash <(curl -s https://codecov.io/bash)
 
script:
 - qmake -project
 - qmake src/BigBlueBox.pro
 - make

# Generate and deploy documentation
after_success:
  #- coveralls --exclude lib --exclude tests --gcov-options '\-lp'
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
