language: cpp
compiler: gcc

sudo: true
dist: trusty
# Blacklist
branches:
  except:
    - gh-pages
    
# Environment variables
env:
  global:
    - GH_REPO_NAME: BigBlueBox
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/rbaker26/BigBlueBox.git
    
# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    
before_install:
  - chmod +x ./scripts/before_install.sh
 - ./scripts/before_install.sh

install:
 - sudo apt-get update
 - sudo apt-get install qt5-default qttools5-dev-tools
 - sudo apt-get install -qq g++-5
 - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
 - sudo pip install codecov
 
script:
 - chmod +x ./scripts/test_build_and_run.sh
 - ./scripts/test_build_and_run.sh
 
 - chmod +x ./scripts/build.sh
 - ./scripts/build.sh
 
 
 
 # This will build the project without tests.
 # It will not run the application because the GUI will timeout.
 - qmake -project
 - qmake src/BigBlueBox.pro
 - make


after_success:
 - chmod +x ./scripts/after_sucess.sh
 - ./scripts/after_sucess.sh
